{{ if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.config | indent 2 }}
{{ end }}
