{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}