{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
{{- $fullName := include "h2o-helm.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2o-helm.labels" . | nindent 4 }}
  {{- if .Values.persistentVolume.annotations }}
  annotations:
    {{- .Values.persistentVolume.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
{{- if .Values.persistentVolume.storageClass }}
{{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: "dsl-kms-block-storage-class"
{{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}
