{{/*

 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "superset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "superset.name" . }}
    chart: {{ template "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.supersetNode.deploymentLabels }}
      {{- toYaml .Values.supersetNode.deploymentLabels | nindent 4 }}
    {{- end }}
    user: {{ .Values.userdata.uuid }}
    alias: {{ .Values.userdata.releaseAlias }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    sharing: {{ .Values.userdata.sharing }}
    service-catalog.ecdp.eu/metadata.service-type: {{ .Chart.Name | lower }}
  {{- if .Values.supersetNode.deploymentAnnotations }}
  annotations: {{- toYaml .Values.supersetNode.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.supersetNode.autoscaling.enabled }}
  replicas: {{ .Values.supersetNode.replicaCount }}
  {{- end }}
  {{- if .Values.supersetNode.strategy }}
  strategy: {{- toYaml .Values.supersetNode.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "supersetNode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force reload on config changes
        checksum/superset_config.py: {{ include "superset-config" . | sha256sum }}
        checksum/superset_init.sh: {{ tpl .Values.init.initscript . | sha256sum }}
        checksum/superset_bootstrap.sh: {{ tpl .Values.bootstrapScript . | sha256sum }}
        checksum/connections: {{ .Values.supersetNode.connections | toYaml | sha256sum }}
        checksum/extraConfigs: {{ .Values.extraConfigs | toYaml | sha256sum }}
        checksum/extraSecrets: {{ .Values.extraSecrets | toYaml | sha256sum }}
        checksum/extraSecretEnv: {{ .Values.extraSecretEnv | toYaml | sha256sum }}
        checksum/configOverrides: {{ .Values.configOverrides | toYaml | sha256sum }}
        checksum/configOverridesFiles: {{ .Values.configOverridesFiles | toYaml | sha256sum }}
        {{- if .Values.supersetNode.forceReload }}
        # Optionally force the thing to reload
        force-reload: {{ randAlphaNum 5 | quote }}
        {{- end }}
        {{- if .Values.supersetNode.podAnnotations }}
          {{- toYaml .Values.supersetNode.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: {{ template "superset.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.supersetNode.podLabels }}
          {{- toYaml .Values.supersetNode.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if or (.Values.serviceAccount.create) (.Values.serviceAccountName) }}
      serviceAccountName: {{ template "superset.serviceAccountName" . }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
        {{- if .Values.supersetNode.podSecurityContext }}
          {{- toYaml .Values.supersetNode.podSecurityContext | nindent 8 }}
        {{- end }}
      {{- if .Values.supersetNode.initContainers }}
      initContainers: {{- tpl (toYaml .Values.supersetNode.initContainers) . | nindent 6 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.supersetNode.containerSecurityContext }}
          securityContext: {{- toYaml .Values.supersetNode.containerSecurityContext | nindent 12 }}
          {{- end }}
          command: {{  tpl (toJson .Values.supersetNode.command) . }}
          env:
            - name: "SUPERSET_PORT"
              value: {{ .Values.service.port | quote}}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.supersetNode.env }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnvRaw }}
              {{- toYaml .Values.extraEnvRaw | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.envFromSecret . | quote }}
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl . $ | quote }}
            {{- end }}
          volumeMounts:
            - name: superset-config
              mountPath: {{ .Values.configMountPath | quote }}
              readOnly: true
            {{- if .Values.extraConfigs }}
            - name: superset-extra-config
              mountPath: {{ .Values.extraConfigMountPath | quote }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- tpl (toYaml .) $ | nindent 12 -}}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.supersetNode.startupProbe }}
          startupProbe: {{- .Values.supersetNode.startupProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.supersetNode.readinessProbe }}
          readinessProbe: {{- .Values.supersetNode.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.supersetNode.livenessProbe }}
          livenessProbe: {{- .Values.supersetNode.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- if .Values.supersetNode.resources }}
              requests:
                cpu: {{.Values.supersetNode.resources.requests.cpu}}
                memory: {{.Values.supersetNode.resources.requests.memory}}
              limits:
                cpu: {{.Values.supersetNode.resources.requests.cpu}}
                memory: {{.Values.supersetNode.resources.requests.memory}}
            {{- else }}
              requests:
                cpu: {{.Values.resources.requests.cpu}}
                memory: {{.Values.resources.requests.memory}}
              limits:
                cpu: {{.Values.resources.requests.cpu}}
                memory: {{.Values.resources.requests.memory}}
            {{- end }}
        {{ if .Values.oauth2Proxy.enabled }}
        - name: oauth2-proxy
          image: {{ .Values.oauth2Proxy.container.image.repository }}:{{ .Values.oauth2Proxy.container.image.tag }}
          imagePullPolicy: {{ .Values.oauth2Proxy.container.image.pullPolicy }}
          ports:
            - name: oauth2-proxy
              containerPort: {{ .Values.oauth2Proxy.container.port | default 4180 }}
              protocol: TCP
          args: {{- if not .Values.oauth2Proxy.container.args }} []
            {{- else if .Values.oauth2Proxy.container.args }}
            {{- toYaml .Values.oauth2Proxy.container.args | nindent 12 }}
            {{- end}}
          env:
            {{- if .Values.oauth2Proxy.container.env }}
            {{- toYaml .Values.oauth2Proxy.container.env | nindent 12 }}
            {{- end}}
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oidc-client
                  key: clientID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oidc-client
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_NAME
              value: {{ .Values.oauth2Proxy.config.cookieName | default (include "superset.fullname" .) }}-oauth2-proxy
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oauth2-proxy
                  key: cookie-secret
            - name: OAUTH2_PROXY_COOKIE_EXPIRE
              value: {{ .Values.oauth2Proxy.config.cookieExpire | default "168h0m0s" | quote }}
            - name: OAUTH2_PROXY_COOKIE_SECURE
              value: {{ .Values.oauth2Proxy.config.cookieSecure | default "true" | quote }}
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: {{ .Values.oauth2Proxy.config.reverseProxy | default "true" | quote }}
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: {{ (.Values.oauth2Proxy.config.httpAddress | default (printf ":%d" (int .Values.oauth2Proxy.container.port)) ) | quote }}
            - name: OAUTH2_PROXY_UPSTREAMS
              value: {{ .Values.oauth2Proxy.config.upstream | default (printf "http://127.0.0.1:%d" (int .Values.service.containerPort )) | quote }}
            - name: OAUTH2_PROXY_PROVIDER
              value: {{ .Values.oauth2Proxy.config.provider | default "keycloak-oidc" | quote }}
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oidc-client
                  key: oidcIssuerUrl
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: {{ .Values.oauth2Proxy.config.redirectUrl | default (printf "https://%s.%s/oauth2/callback" (include "superset.fullname" .) (index .Values.ingress.hosts 0).host) | quote }}
            - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
              value: {{ .Values.oauth2Proxy.config.codeChallengeMethod | default "S256" | quote }}
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: {{ .Values.oauth2Proxy.config.skipProviderButton | default "true" | quote }}
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: {{ .Values.oauth2Proxy.config.emailDomain | default "*" | quote }}
            - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
              value: {{ .Values.oauth2Proxy.config.insecureOidcAllowUnverifiedEmail | default "true" | quote }}
            - name: OAUTH2_PROXY_ALLOWED_ROLES
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oidc-client
                  key: allowedRoles
            - name: OAUTH2_PROXY_ALLOWED_GROUPS
              valueFrom:
                secretKeyRef:
                  name: {{ template "superset.fullname" . }}-oidc-client
                  key: allowedGroups
          resources:
            limits:
              cpu: {{ .Values.oauth2Proxy.container.resources.requests.cpu }}
              memory: {{ .Values.oauth2Proxy.container.resources.requests.memory }}
            requests:
              cpu: {{ .Values.oauth2Proxy.container.resources.requests.cpu }}
              memory: {{ .Values.oauth2Proxy.container.resources.requests.memory }}
        {{- end }}  
        {{- if .Values.supersetNode.extraContainers }}
          {{- toYaml .Values.supersetNode.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity .Values.supersetNode.affinity }}
      affinity:
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.supersetNode.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.topologySpreadConstraints .Values.supersetNode.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- with .Values.topologySpreadConstraints }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.supersetNode.topologySpreadConstraints }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: superset-config
          secret:
            secretName: {{ tpl .Values.configFromSecret . }}
        {{- if .Values.extraConfigs }}
        - name: superset-extra-config
          configMap:
            name: {{ template "superset.fullname" . }}-extra-config
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- tpl (toYaml .) $ | nindent 8 -}}
        {{- end }}
