{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "superset.fullname" . }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}