{{- if .Values.image.deployRegistry -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Release.Name }}-{{ .Values.image.name }}-{{ .Values.image.imagePullSecrets }}"
  namespace: {{ .Release.Namespace  }}
data:
  .dockerconfigjson: {{ .Values.image.dataSecret | b64enc }}
{{- end -}}
